name: Version / Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: git config --global user.name clout-tools
      - run: git config --global user.email ${{ secrets.SECRET_EMAIL }}
      - run: git fetch origin main
      - run: npm run workspace:version
      - run: npm run deploy:package
